$mainMod = ALT

bind = $mainMod, H , movefocus, l
bind = $mainMod, J, movefocus, d
bind = $mainMod, K, movefocus, u
bind = $mainMod, L, movefocus, r

# bind = $mainMod, F, exec, ~/.config/hypr/scripts/gamemode.sh
bind = $mainMod, X, exec, ~/.config/hypr/scripts/dontkillsteam.sh
bind = $mainMod, W, togglefloating,
bind = $mainMod, C, exec, hyprpicker -a
bind = $mainMod, S, exec, slack
bind = $mainMod, Q, exec, pkill rofi || ~/.config/hypr/scripts/rofilaunch.sh w
bind = $mainMod, F, exec, pkill rofi || ~/.config/hypr/scripts/rofilaunch.sh f

bind = $mainMod, space, exec, pkill rofi || ~/.config/hypr/scripts/rofilaunch.sh d
bind = $mainMod, Tab, movefocus, d
bind = $mainMod, return, exec, kitty

bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

binde = $mainMod, right, resizeactive, 10 0
binde = $mainMod, left, resizeactive, -10 0
binde = $mainMod, up, resizeactive, 0 -10
binde = $mainMod, down, resizeactive, 0 10

bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

bind = $mainMod, B, exec, firefox
bind = $mainMod, E, exec, microsoft-edge-stable

bind  =  , F11,fullscreen ,
bind  = , XF86AudioMute, exec, ~/.config/hypr/scripts/volumecontrol.sh -o m
bind  = , XF86AudioMicMute, exec, ~/.config/hypr/scripts/volumecontrol.sh -i m
bind  = , XF86AudioPlay, exec, playerctl play-pause
bind  = , XF86AudioPause, exec, playerctl play-pause
bind  = , XF86AudioNext, exec, playerctl next
bind  = , XF86AudioPrev, exec, playerctl previous
binde = , XF86AudioLowerVolume, exec, ~/.config/hypr/scripts/volumecontrol.sh -o d
binde = , XF86AudioRaiseVolume, exec, ~/.config/hypr/scripts/volumecontrol.sh -o i
binde = , XF86MonBrightnessUp, exec, ~/.config/hypr/scripts/brightnesscontrol.sh i
binde = , XF86MonBrightnessDown, exec, ~/.config/hypr/scripts/brightnesscontrol.sh d

bind = , Print, exec, grim -g "$(slurp)" - | wl-copy  | dunstify 'Screenshot!' 'Will be Copied to Clipboard' -a 'System' -i '~/.config/dunst/icons/screenshot.svg' -t '2000'

bind = SUPER, E, exec, dolphin
bind = SUPER, V, exec, ~/.config/hypr/scripts/cliphist.sh c ${mod_pos}

bind = SUPER, backspace, exec, wlogout -b 3 -c 0 -r 0 -L 680 -R 680 -T 360 -B 360 --protocol layer-shell

bind = SUPER_SHIFT, backspace, exit,
bind = SUPER_SHIFT, L, exec, swaylock

bind = SHIFT, Print, exec, grim ~/Pictures/Screenshots/$(date +'%y%m%d_%Hh%Mm%Ss_screenshot.png') | dunstify 'Screenshot Saved!' 'In ~/Pictures/Screenshot' -a 'System' -i '~/.config/dunst/icons/screenshot.svg' -t '2000'

bind = $mainMod_SUPER, right, exec, ~/.config/swww/swwwallpaper.sh -n
bind = $mainMod_SUPER, left, exec, ~/.config/swww/swwwallpaper.sh -p
bind = $mainMod_SUPER, up, exec, ~/.config/waybar/wbarconfgen.sh n
bind = $mainMod_SUPER, down, exec, ~/.config/waybar/wbarconfgen.sh p
bind = $mainMod_SUPER, T, exec, ~/.config/hypr/scripts/themeswitch.sh -n
bind = $mainMod_SUPER, A, exec, ~/.config/hypr/scripts/rofiselect.sh
